services:

  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - '3306:3306'
